"""add_onboarding_fields

Revision ID: bfa5f73d8589
Revises: 1d0c0995693c
Create Date: 2025-11-29 13:29:24.656611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa5f73d8589'
down_revision = '1d0c0995693c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_data')
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
